### ISSUE TITLE
Should the message printed include quotes in them?

### ISSUE THREAD

**Issue by benspector-mls** [The-Marcy-Lab-School/1-2-1-assignment#1]
https://github.com/The-Marcy-Lab-School/1-2-1-assignment/blob/48155231daa1bc60bd4adcc8a2b71bbe1b39a6b8/src/from-scratch.spec.js#L35-L37

**Comment by MostlyFocusedMike** [comment]
Nope! I think you're right, I probably copied that in from the readme, so I removed the extra quotes and the tests still pass so we're good!
